### ISSUE TITLE
Apparent host renaming issues in Win2k8R2 / distro-specificity

### ISSUE THREAD

**Issue by leftathome** [WinRb/vagrant-windows#5]
I'm not sure how many people run into this issue, but I can't seem to get a Windows 2008R2 guest to take a rename.  I need to be able to rename VMs in order to run the Chef client on them.

Has anyone already gotten system renaming to work?  Does the code in Vagrant::Guest::Windows.change_host_name() already work for anybody?  I'm happy to send a pull request if not.

I using the netdom command to do the host renaming and kicking off a reboot with the shutdown command.  The reboot is, unfortunately, mandatory for the rename to fully take effect.  These commands appear to date back only to around Win2k3, so those interested in running older versions might still be out of luck even with my changes.

I haven't even thought about making any of this work in Active Directory, BTW.

To accommodate further Windows-version-specific behavior, I've made a couple of ham-fisted attempts to determine what version of Windows is running based on a WMI call and feed that to Vagrant::Guest::Windows.distro_dispatch() ... honestly, I'm hoping that I can just get the basic info out there and someone who spends more time in Windows than I have for the last few years could carry the ball the rest of the way... I can offer this code in the same pull request or separately if you're interested.

Thanks!

**Comment by biagit** [comment]
I think that you hit the nail on the head with regard to rebooting. The current workflow does not support the idea that you need to reboot a host to rename it. In my mind it seems that it might make sense to use a middleware approach to renaming the machine so that we can anticipate the fact that the machine needs to be renamed and rebooted prior to provisioning.  

http://vagrantup.com/v1/docs/extending/middleware.html

Thoughts?

**Comment by leftathome** [comment]
Problem solved through pull request #6 ... though perhaps this approach could be revisited when the day comes that this entire codebase has to be refactored against the newfangled Vagrant 1.1 plugin architecture?
